# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    environment:
      PYTHON_PATH: .:vendor
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password

      # MYSQL
      # https://hub.docker.com/r/circleci/mysql/
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_DATABASE: bugs
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: %
          MYSQL_USER: root
          MYSQL_PASS: password

      # ELASTICSEARCH
      # https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docker.html
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
        environment:
          cluster.name: docker-cluster
          bootstrap.memory_lock: true
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - esdata1:/usr/share/elasticsearch/data
        ports:
          - 9200:9200



    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          environment:
            PYTHONPATH: .:vendor
            TEST_CONFIG: tests/resources/config/circleci.json
          command: |
            . venv/bin/activate
            python -m unittest discover -v -s tests

      - store_artifacts:
          path: test-reports
          destination: test-reports
